### ISSUE TITLE
Customize options for sanitize-html

### ISSUE THREAD

**Issue by dawnerd** [shivanshu3/strip-js#2]
Would be nice to be able to override the defaults. Would be handy for locking down to a smaller set of allowed elements.

I'd love to do a PR for it too.

**Comment by shivanshu3** [comment]
Yup, that would definitely be a nice addition to it!
I guess adding a second optional argument to the `stripJs` function which gets passed down to sanitize-html would suffice?
We would just have to make sure that the `javascript` scheme isn't part of the `allowedSchemes` option or the `allowedSchemesByTag` option.

**Comment by shivanshu3** [comment]
Fixed by PR #4
